Initial forum structure
edx/frontend-app-discussions pull request #1
Opened 2020-08-12 20:19 UTC by xitij2000

2020-08-12 20:19 UTC, edx-webhook commented
Thanks for the pull request, @xitij2000! I've created [OSPR-4895](https://openedx.atlassian.net/browse/OSPR-4895) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

Please let us know once your PR is ready for our review and all tests are green.



<!-- comment:external_pr -->
<!-- jenkins ok to test -->

2020-09-07 09:17 UTC, xitij2000 commented
@stvstnfrd  This is the base forum structure in which other PRs will be merged. It has the very basics working, but a lot of changes are coming in future PRs. This is based on a slightly older design, but that will be rectified in the rest of the PRs.

2020-10-07 18:09 UTC, stvstnfrd approved these changes
Two nitpicks, but otherwise nothing controversial, :+1:

2020-10-07 18:09 UTC, stvstnfrd commented on .eslintignore
> +jest.config.js
Nit: Can you add trailing newline here?

2020-10-07 18:09 UTC, stvstnfrd commented on .eslintrc.js
> +module.exports = createConfig('eslint');
Nit: Can you add trailing newline here?

2020-10-07 23:12 UTC, xitij2000 commented on .env.development
> +PORT=2002
@stvstnfrd  I picked this port as learning is 2000, and authoring is 2001 so I just picked the next one.

2020-10-14 14:35 UTC, stvstnfrd requested changes

2020-10-14 14:35 UTC, stvstnfrd commented on .env.test
> +BASE_URL='localhost:1995'
It also looks like `PORT` isn't defined in this file either.
Are there other settings missing? Was this intentional or an issue w/ the template/cookiecutter?

2020-10-15 10:33 UTC, xitij2000 commented on .env.test
> +BASE_URL='localhost:1995'
I have not touched this file, so it's probably because of the template.

2020-10-21 08:45 UTC, xitij2000 commented
@stvstnfrd If this seems OK to you could you give it a thumbs-up so I can merge it?

2020-10-23 12:03 UTC, 0x29a approved these changes
:+1:

- [x] I tested that new discussions frontend loads fine and has basic structure, like forums and threads.
- [x] I read through the code
- [ ] ~I checked for accessibility issues~
- [ ] ~Includes documentation~
- [ ] ~I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.~

2020-10-23 12:05 UTC, merged