[WIP][BB-4735][TNL-8657] Add comment pagination
edx/frontend-app-discussions pull request #17
Opened 2021-09-10 11:54 UTC by Cup0fCoffee

2021-09-10 11:54 UTC, edx-webhook commented
Thanks for the pull request, @Cup0fCoffee! I've created [OSPR-6036](https://openedx.atlassian.net/browse/OSPR-6036) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

<!-- comment:end_of_wip -->




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IHRydWV9 -->

2021-09-10 16:37 UTC, natabene commented
@Cup0fCoffee Thank you for your contribution. Please let me know once it is ready for our review.

2021-09-14 04:00 UTC, xitij2000 commented on src/discussions/comments/CommentsView.jsx
> +  const [currentPage, setCurrentPage] = useState(1);
Each time we load comments, store the loaded page for the thread, and just add ids to the end of the previous array. The reducers can check if the current page === last page, then set the all pages loaded flag.

2021-09-15 05:30 UTC, xitij2000 requested changes

2021-09-15 05:30 UTC, xitij2000 commented on src/discussions/comments/CommentsView.jsx
> +  }, [currentPage]);
This should depend on both the currentPage and postId, otherwise the same posts will be displayed as you change posts.

2021-09-15 05:30 UTC, xitij2000 commented on src/discussions/comments/CommentsView.jsx
> +  }, [currentPage]);
Unfortunately, even with that change, we see old comments as we switch from one post to another. I think we will need to have pagination on a per-post level. 
i.e. sturcture pagination as follows

```
state.pagination = {
   [postId]: {
       currentPage: number,
       totalPages: numner,
       ids: []
  }
}
```

2021-09-15 10:40 UTC, closed without merging

2021-09-15 10:40 UTC, edx-webhook commented
@Cup0fCoffee Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/frontend-app-discussions&entry.867055334=https://github.com/edx/frontend-app-discussions/pull/17&entry.1484655318=https://github.com/Cup0fCoffee&entry.752974735=2021-09-10+11:54&entry.1917517419=2021-09-15+10:40&entry.2133058324=No) so we can improve your experience in the future.

<!-- comment:end_survey -->