[BD-03] [TNL-7414] [BB-2855] Discussion APIs redux integration etc.
edx/frontend-app-discussions pull request #3
Opened 2020-08-21 16:07 UTC by xitij2000

This PR adds all the data APIs and redux boilerplate for discussions.

**JIRA tickets**: TNL-7414

**Dependencies**: https://github.com/edx/frontend-app-discussions/pull/1

**Sandbox URL**: NA

**Testing instructions**:

For the purpose of testing the internals of redux have been exposed to allow working via the browser console since this only adds internal APIs. All API methods have been added to window.api, all thunks to window.thunks and the store has been added as well.

For instance you can test the comment adding feature by running the following in your browser console:
``store.dispatch(thunks.addComment("test comment", <thread_id>))``

If you have the comments page open at this time you can see the comment appear in real-time.

**Reviewers**
- [ ] @pcockwell
- [ ] edX reviewer[s] TBD

2020-08-24 11:22 UTC, pcockwell requested changes

2020-08-24 11:22 UTC, pcockwell commented on src/discussions/posts/data/api.js
> +], 'Comments API service');
Should this be `Posts API service`?

2020-08-24 11:22 UTC, pcockwell commented on src/discussions/utils.js
> +}
This doesn't appear to be used anywhere - should it be removed?

2020-08-24 11:40 UTC, pcockwell commented on src/discussions/posts/data/thunks.js
> +      dispatch(postThreadSuccess({ threadId }));
This needs to be `deleteThreadSuccess`

2020-08-24 11:41 UTC, pcockwell commented
I tested the following `thunks` methods:

```
addComment
editComment
removeComment
createNewThread
updateExistingThread
removeThread
```

All of them worked, with the exception of `removeThread`, which did still remove the thread, but failed to update the UI. I've added a comment where the necessary change for that needs to be. I have not yet tested any fetch methods given that there are no return values, or UI changes from them

2020-08-24 12:30 UTC, xitij2000 commented
@pcockwell I've pushed an update that addresses your points

2020-08-24 13:25 UTC, pcockwell approved these changes
:+1: Approving dependent on the merging of #1  

- [x] I tested this: I tested these thunks methods:
```
addComment
editComment
removeComment
createNewThread
updateExistingThread
removeThread
```
- [x] I read through the code

2020-11-04 22:06 UTC, giovannicimolin approved these changes
:+1:

- [x] I tested this:
1. Checked that the code builds when using Node v14.15.0 (LTS).
2. Checked that the API calls were working. I've tested `api.getThreads` directly and `addComments` through a store dispatch method (then checked that the comment was created in the LMS discussions tab).
- [ ] I read through the code: no, this was already reviewed before.
- [ ] ~~I checked for accessibility issues~~ NA
- [ ] Includes documentation: No.

@xitij2000 Based on the previous approval, this is good to go.
I've checked that the builds work and that the API methods are working fine.

2020-11-06 09:19 UTC, merged